.\" Copyright (c) 2013, Vrai Stacey
.\" 
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version 2
.\" of the License, or (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
.\" 02110-1301, USA.
.\"
.\" ===================================================================
.\"
.TH "cpuspin" 1 "2013 August 20"
.SH "NAME"
cpuspin \- loads a single CPU as heavily as possible for a limited time.
.\"
.\" ===================================================================
.\"
.SH "SYNOPSIS"
.B cpuspin
\fIseconds\fP
.\"
.\" ===================================================================
.\"
.SH "DESCRIPTION"
The \fBcpuspin\fP tool is simply a tight loop with the occasional time
check. Within this loop a division and \fBsqrt\fP operation is applied
to a set of random numbers. In normal operation this will result in an
(uncontended) CPU core maxing out for the duration of the run.
.sp
Note that exact timing of the run is not guaranteed. Overall machine
load could result in the tool running for slightly longer than the
specified number of seconds.
.\"
.\" ===================================================================
.\"
.SH "AUTHOR"
Copyright \(co 2013, Vrai Stacey <vrai.stacey@gmail.com>
